
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private Gtk.UIManager UIManager;
	
	private Gtk.Action FileAction;
	
	private Gtk.VBox vbox1;
	
	private Gtk.MenuBar menubar2;
		
	private Gtk.Table table1;
	
	private Gtk.ScrolledWindow GtkScrolledWindow;
	
	private Gtk.TextView textview_seqnames;
	
	private Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private Gtk.TextView textview_seqs;

	protected virtual void Build ()
	{
		Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new Gtk.UIManager ();
		Gtk.ActionGroup w1 = new Gtk.ActionGroup ("Default");
		this.FileAction = new Gtk.Action ("FileAction", "File", null, null);
		this.FileAction.ShortLabel = "File";
		w1.Add (this.FileAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "ccsviewer";
		this.Title = "CCS Viewer";
		this.WindowPosition = ((Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'/></menubar></ui>");
		this.menubar2 = ((Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;

		// Create Table
		this.table1 = new Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));

		// Seq Names Window
		this.GtkScrolledWindow = new Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
		this.textview_seqnames = new Gtk.TextView ();
		this.textview_seqnames.CanFocus = true;
		this.textview_seqnames.Name = "textview_seqnames";
		this.GtkScrolledWindow.Add (this.textview_seqnames);
		this.table1.Add (this.GtkScrolledWindow);
        // Update table positions
		Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(3));
        w4.LeftAttach = ((uint)0);
        w4.RightAttach = ((uint)1);
//        w4.XOptions = (Gtk.AttachOptions.Expand);


        // Alignment Window
		this.GtkScrolledWindow1 = new Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview_seqs = new Gtk.TextView ();
		this.textview_seqs.CanFocus = true;
		this.textview_seqs.Name = "textview_seqs";
		this.GtkScrolledWindow1.Add (this.textview_seqs);
		this.table1.Add (this.GtkScrolledWindow1);
		Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow1]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(3));
		
        // Add table
        this.vbox1.Add (this.table1);
		Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w8.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 741;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.FileAction.Activated += new System.EventHandler (this.activateSignal);
	}
}
